version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ufficient
      POSTGRES_PASSWORD: ufficient_pass
      POSTGRES_DB: ufficientdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgres://ufficient:ufficient_pass@db:5432/ufficientdb
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: development
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db-data:
