name: Deploy Ufficient V1
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      target:
        description: "Which app to deploy"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - landing
          - admin
          - pwa

jobs:
  deploy-landing:
    name: Build & Deploy Landing
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.target == 'landing' || inputs.target == 'all' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Type Check (Landing)
        run: npm run type-check --workspace=apps/landing

      - name: Lint (Landing)
        run: npm run lint --workspace=apps/landing

      - name: Build (Landing)
        run: npm run build --workspace=apps/landing
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: Deploy Landing to Vercel
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_LANDING_PROJECT_ID }}
          working-directory: ./apps/landing
          vercel-args: '--prod'

  deploy-admin:
    name: Build & Deploy Admin
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.target == 'admin' || inputs.target == 'all' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Type Check (Admin)
        run: npm run type-check --workspace=apps/admin

      - name: Lint (Admin)
        run: npm run lint --workspace=apps/admin

      - name: Build (Admin)
        run: npm run build --workspace=apps/admin
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_CLIENT_ID: ${{ secrets.FIREBASE_CLIENT_ID }}
          FIREBASE_CLIENT_CERT_URL: ${{ secrets.FIREBASE_CLIENT_CERT_URL }}

      - name: Deploy Admin to Vercel
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_ADMIN_PROJECT_ID }}
          working-directory: ./apps/admin
          vercel-args: '--prod'

  deploy-pwa:
    name: Build & Deploy PWA
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.target == 'pwa' || inputs.target == 'all' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Type Check (PWA)
        run: npm run type-check --workspace=apps/mobile-pwa

      - name: Lint (PWA)
        run: npm run lint --workspace=apps/mobile-pwa

      - name: Build (PWA)
        run: npm run build --workspace=apps/mobile-pwa
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: Deploy PWA to Vercel
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PWA_PROJECT_ID }}
          working-directory: ./apps/mobile-pwa
          vercel-args: '--prod'

  # Disable native app build for now
  native-app-check:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Skipped
        run: echo "Native app build is disabled for now"
